name: kaya

services:
  kaya:
    image: ${KAYA_IMAGE:-ghcr.io/antybubbs/kaya:latest}
    container_name: kaya
    restart: unless-stopped
    environment:
      DATABASE_URL: sqlite:////app/data/kaya.db
      ALLOWED_HOSTS: ${ALLOWED_HOSTS:-localhost,127.0.0.1,kaya,homelab}
    ports:
      - "${KAYA_BIND:-127.0.0.1}:${KAYA_PORT:-8080}:8080"
    volumes:
      - ./data:/app/data
      - ./uploads:/app/uploads
      - ./data/remote-recordings:/app/data/remote-recordings
    security_opt:
      - no-new-privileges:true
    cap_add:
      - NET_RAW
    read_only: true
    tmpfs:
      - /tmp:size=128m,noexec,nosuid
  guacd:
    image: guacamole/guacd:1.6.0
    container_name: kaya-guacd
    restart: unless-stopped

networks:
  default:
    driver: bridge
    driver_opts:
      # Match default WireGuard MTU so large RDP graphics packets do, this helps if you are running kaya in a VPN container and the VPN is using WireGuard. 
      # Otherwise, you may experience issues with RDP graphics when using kaya through a VPN. 
      # This is because WireGuard uses a 1420-byte MTU, which is smaller than the default Docker bridge MTU of 1500 bytes. 
      # By setting the MTU to 1280 bytes, we can avoid fragmentation and ensure that large packets are transmitted correctly. If you are not using a VPN, you can remove this option or set it to 1500 bytes.
      com.docker.network.driver.mtu: "1280"
